---
title: "clinical_description"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{clinical_description}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/clinical_description/",
  fig.width = 12,
  fig.height = 6,
  dpi = 300
)
```

```{r setup}
library("hlebuhanec.0325")
library("GimmeMyStats")
library("GimmeMyPlot")
library("GimmeMyOmics")
library("RColorBrewer")
library("rlist")
library("ggrepel")
library("kableExtra")
library("cowplot")
library("janitor")
library("naniar")
library("openxlsx")
plot_heatmap <- GimmeMyPlot::plot_heatmap
data("clinic2")

path_fig <- file.path(getwd(),  knitr::opts_chunk$get("fig.path"))

func_format <- function(x) {
  str_replace_all(x, "_", " ") %>%
  str_to_sentence() %>%
  str_replace_all("micro l", "\\(ml\\)") %>%
  str_replace_all("mm3", "\\(mm3\\)")
}
```

```{r}
table(clinic2$groupe) %>%
    enframe(name = "Group", value = "N") %>%
    kable0()

select(clinic2, -ipp) %>%
  write_statistics(file = file.path(path_fig, "statistics.xlsx"), format = function(x) func_format(x))
```

## Demography
```{r, fig.width = 16, fig.height = 8}
list.map(
  unique(clinic2$groupe),
  f(x) ~ {
    res <- filter(clinic2, groupe == x) %>%
    filter(!is.na(age), !is.na(sexe)) %>%
    age_pyramid("age", "sexe", seq(0, 100, 10), colour = brewer.pal(4, "Paired")[3:4]) + 
    ggtitle(x) +
    theme(plot.title = element_text(hjust = 0.5, face = "bold"))
  plot(res)
  }) %>%
  plot_grid(plotlist = ., ncol = 3)
```

```{r}
plot_bar_2cat(
  select(clinic2, "sexe", "groupe"),
  sort = c("HD", "DA", "PN"),
  stats = FALSE
)
filter(clinic2, is.na(sexe)) %>% select(patient)

list.map(
  c("age", "age_au_dg_an"),
  f(x, y) ~ {
    res <- clinic2 %>%
  select(all_of(c(x, "groupe", "patient")))
    if (y == 2)
      res <- filter(res, groupe != "HD")
  pivot_wider(res, names_from = groupe, values_from = !!sym(x)) %>%
  column_to_rownames("patient") %>%
  plot_violin(
    colour = palette_discrete()[seq(length(unique(res$groupe)))],
    cex = 1.2,
    pch_size = 3,
    pch_alpha = 0.25,
    coef = 1.5,
    breaks = c(25, 50, 75),
    label = TRUE,
    title = ifelse(y < 2, "Age", "Age at diagnostic")
  )
  }
) %>%
  plot_grid(plotlist = ., ncol = 2)

table_groupe_numeric(clinic2, c("age", "age_au_dg_an"), file.path(path_fig, paste0("stats_age.png")))

filter(clinic2, is.na(age)) %>% 
  select(patient)

filter(clinic2, is.na(age_au_dg_an)) %>% 
    filter(groupe != "HD") %>%
    select(patient)
```

## Timelines
```{r}
date_variables <- find_dates(clinic2)
list.map(
  date_variables,
  f(x, y) ~{
    if (y != 2){
      regex <- "%Y-%m"
    } else {
      regex <- "%Y"
    }
    pull(clinic2, x) %>%
      plot_date(
        func = ymd,
        title = func_format(x),
        regex = regex
      )
  }
)
```

```{r}
list.map(
  unique(clinic2$groupe),
  f(i) ~ {
    res <- filter(clinic2, groupe == i)
  list.map(
    date_variables,
    f(x, y) ~{
      if (y != 2){
        regex <- "%Y-%m"
      } else {
        regex <- "%Y"
      }
      pull(res, x) %>%
        plot_date(
          func = ymd,
          title = paste(i, ":", str_replace_all(x, "_", " ") %>% str_to_sentence()),
          regex = regex
        )
    }
  )
  }
)
```

```{r, fig.width = 20, fig.height = 10}
list.map(
  date_variables[-5],
  f(x, y) ~ {
clinic2 %>%
    mutate(
    years = pull(., x) %>% 
        year() %>% as.character()
)  %>%
    select(years, groupe) %>%
    plot_bar_2cat(
        sort = c("HD", "DA", "PN"),
        stats = FALSE,
        threshold_pct = 10,
        title = func_format(x)
    ) -> res
  }
) %>% plot_grid(plotlist = ., ncol = 2)
```

```{r}
p <- list.map(
  find_dates(clinic2)[-5],
  f(x, y) ~ {
    print(x)
    if(y %in% c(3, 4)) {
      res <- filter(clinic2, groupe != "HD")
    } else {
      res <- clinic2
    }
    if (y == 1) {
      res <- res %>%
      mutate(
        days = pull(., all_of(x)) %>% 
        difftime(Sys.Date(), .) %>% 
        as.numeric()
        ) 
    } else {
      res <- res %>%
      mutate(
        days = pull(., all_of(x)) %>% 
        difftime(pull(res, "date_inclusion"), ., units = "days") %>% 
        as.numeric()
        )
    }
    select(res, days, groupe, patient) %>%
    pivot_wider(names_from = groupe, values_from = days) %>%
    column_to_rownames("patient") %>%
    plot_violin(
      colour = palette_discrete()[seq(length(unique(pull(res, "groupe"))))],
      cex = 1.2,
      pch_size = 3,
      pch_alpha = 0.25,
      coef = 1.5,
      label = TRUE,
      width_text = 20,
      title = func_format(x),
      func_label = label_date,
      ratio_labs = 1
    ) -> res
    plot(res)
  }
)
```

### Errors in age
```{r}
clinic2 %>%
    mutate(
        age_years = as.numeric(difftime(date_inclusion, date_naissance, units = "days")) / 365.25
    ) %>% 
    mutate(diff_age = age_years - age) %>% 
    column_to_rownames("patient") -> res
select(res, diff_age) %>%
    plot_violin(label = TRUE)
filter(res, abs(diff_age)  > 1.5) %>% select(date_naissance, age_years, age, diff_age) %>% kable0(digits = 1)
```

## Biologic
```{r, fig.width = 23, fig.height = 10}
vars0 <- c("pne_mm3", "pnn", "monocytes", "cd4_micro_l", "cd8_micro_l", "ly_b_micro_l", "plaquettes", "creatinine")
vars <- c(vars0, str_subset(colnames(clinic2), "ig_"))
vars1 <- c(vars, "cd_ratio")
vars2 <- c(vars0, "cd_ratio")
func_format2 <- function(x) {
  str_replace_all(x, "_", " ") %>%
  str_to_upper() %>%
  str_replace_all("MICRO L", "\\(ml\\)") %>%
  str_replace_all("MM3", "\\(mm3\\)") %>%
  str_replace_all("IG", "Ig")
}

clinic3 <- mutate(clinic2, cd_ratio = cd4_micro_l / cd8_micro_l)

p <- filter(clinic3, groupe != "HD") %>%
  plot_violin_group(
    vars1,
    func_format2,
    method = "wilcox",
    display_log = TRUE
  )
plot_grid(plotlist = p[seq(8)], ncol = 4, align = "hv")
plot_grid(plotlist = p[-seq(8)], ncol = 4, align = "hv")
```

```{r}
table_groupe_numeric(clinic3, vars1, file.path(path_fig, paste0("stats_biol.png")), format = func_format2)
```

```{r}
filter(clinic3, groupe != "HD") %>%
  mutate(across(vars2, ~ (. - min(., na.rm = TRUE)) / (max(., na.rm = TRUE) - min(., na.rm = TRUE)) * 100)) %>%
  plot_radar_clinic(vars2, func = func_format2)
```

```{r, fig.width = 20, fig.height = 10}
filter(clinic3, groupe != "HD") %>%
    plot_heatmap_clinic(vars1, func = func_format2)
filter(clinic3, groupe != "HD") %>%
    plot_heatmap_clinic(vars1, normalize = "minmax", func = func_format2)
```

```{r}
clinic3 <- select(clinic2, c(all_of(vars0), "groupe")) %>% 
    rename_all(func_format2)
select(clinic3, -GROUPE) %>%
  plot_mcor()

p <- list.map(
  c("DA", "PN"),
  f(i) ~filter(clinic3, GROUPE == i) %>%
  select(-GROUPE) %>%
  plot_mcor() +
    ggtitle(i)
)
p
```

```{r}
select(clinic3, -GROUPE) %>% 
  plot_cor_network(cutoff = .4, dyn = FALSE, label = TRUE)
```

```{r}
plot_top_cor(clinic2, vars0, func_format2) %>%
  plot_grid(plotlist = .)

p <- list.map(
  c("DA", "PN"),
  f(i) ~filter(clinic2, groupe == i) %>%
  plot_top_cor(vars0, func_format2, cutoff = .4) %>%
  plot_grid(plotlist = .)
)
p
```

```{r}
metada_samples(clinic2, c("DA35", "DA04", "PN02", "PN03", "PN09"))
```

## Scores
```{r}
func_format2 <- function(x) {
  str_replace_all(x, "_", " ") %>%
          str_to_upper() %>%
          str_replace_all("POST TTT", "post-traitement")
}

filter(clinic2, groupe != "HD") %>%
 plot_violin_group(c("dlqi", str_subset(colnames(clinic2), "eva_")), func = func_format2) %>%
    plot_grid(plotlist = ., ncol = 3)
# [0-30]; [0-10]
# severe: >10; > 6

filter(clinic2, groupe == "DA") %>%
 plot_violin_group(str_subset(colnames(clinic2), "easi_"), func = func_format2) %>%
    plot_grid(plotlist = .)
# [0-72]
# severe: >21
```

```{r}
res <- list(
  filter(clinic2, easi_da < 20),
  filter(clinic2, dlqi < 10) ,
  filter(clinic2, eva_prurit < 6)
) %>%
  map(~pull(., patient)) %>%
  set_names(c("easi_da", "dlqi", "eva_prurit") %>% func_format2())

filter(clinic2, easi_da < 20 | dlqi < 10 | eva_prurit < 6 | eva_prurit_post_ttt > 6) %>% 
  pull(patient) %>%
  
```


```{r, fig.width = 20, fig.height = 10}
filter(clinic2, groupe != "HD") %>%
    plot_heatmap_clinic(c("dlqi", "eva_prurit", "easi_da"), func = func_format2)

filter(clinic2, groupe == "PN") %>%
    plot_heatmap_clinic(c("dlqi", "eva_prurit", "easi_da"), func = func_format2) +
    scale_fill_gradientn(
        colours = rev(brewer.pal(11, "RdBu")),
        limits = c(-3.5, 2.5),
        na.value = "white",
        oob = scales::squish
    )
```

```{r}
library(scatterplot3d)

data_3d <- clinic2 %>%
    filter(groupe == "DA") %>%
    select(c("patient", "dlqi", "eva_prurit", "easi_da")) %>%
    # mutate(across(c(dlqi, eva_prurit, easi_da), ~ ifelse(is.na(.), median(., na.rm = TRUE), .))) %>%
    na.omit() %>%
    mutate(
        minmax_dlqi = (dlqi - min(dlqi, na.rm = TRUE)) / (max(dlqi, na.rm = TRUE) - min(dlqi, na.rm = TRUE)),
        minmax_eva_prurit = (eva_prurit - min(eva_prurit, na.rm = TRUE)) / (max(eva_prurit, na.rm = TRUE) - min(eva_prurit, na.rm = TRUE)),
        minmax_easi_da = (easi_da - min(easi_da, na.rm = TRUE)) / (max(easi_da, na.rm = TRUE) - min(easi_da, na.rm = TRUE)),
        median_minmax = rowMeans(cbind(minmax_dlqi, minmax_eva_prurit, minmax_easi_da))
    )

colour_palette <- colorRampPalette(c(brewer.pal(4, "Reds")[-1] %>% rev(), "grey", brewer.pal(4, "Blues")[-1]) %>% rev())(nrow(data_3d))
colour_gradient <- colour_palette[rank(data_3d$median_minmax)]

s3d <- scatterplot3d(
    x = data_3d$dlqi,
    y = data_3d$eva_prurit,
    z = data_3d$easi_da,
    xlab = "DLQI",
    ylab = "EVA Prurit",
    zlab = "EASI DA",
    pch = "",
    color = colour_gradient,
    main = "3D Scatter Plot"
)

coords <- s3d$xyz.convert(data_3d$dlqi, data_3d$eva_prurit, data_3d$easi_da)

text(
    x = coords$x,
    y = coords$y,
    labels = data_3d$patient,
    col = colour_gradient,
    cex = 0.8
)

library(plotly)

plot_ly(
    data = data_3d,
    x = ~dlqi,
    y = ~eva_prurit,
    z = ~easi_da,
    type = "scatter3d",
    mode = "text",
    text = ~patient,
    textfont = list(color = colour_gradient, size = 12)
) %>%
    layout(
        title = "3D Scatter Plot",
        scene = list(
            xaxis = list(title = "DLQI"),
            yaxis = list(title = "EVA Prurit"),
            zaxis = list(title = "EASI DA")
        )
    )
```


```{r}
data_2d <- clinic2 %>%
    filter(groupe == "PN") %>%
    select(c("patient", "dlqi", "eva_prurit")) %>%
    mutate(
        minmax_dlqi = (dlqi - min(dlqi, na.rm = TRUE)) / (max(dlqi, na.rm = TRUE) - min(dlqi, na.rm = TRUE)),
        minmax_eva_prurit = (eva_prurit - min(eva_prurit, na.rm = TRUE)) / (max(eva_prurit, na.rm = TRUE) - min(eva_prurit, na.rm = TRUE)),
        median_minmax = rowMeans(cbind(minmax_dlqi, minmax_eva_prurit), na.rm = TRUE)
    )

ggplot(data_2d, aes(x = dlqi, y = eva_prurit, label = patient, colour = median_minmax)) +
    geom_text_repel(size = 3) +
    scale_colour_gradientn(
    colours = c(brewer.pal(4, "Blues")[-1] %>% rev(), "grey", brewer.pal(4, "Reds")[-1]),
    name = "Median min-max"
) +
    labs(x = "DLQI", y = "EVA Prurit", title = "2D Scatter Plot") +
    theme_classic() +
    theme_custom()

c("DA41", "DA15", "DA09", "DA18", "PN08", "PN10", "PN30", "PN35", "PN17", "PN22") %>% metada_samples(clinic2, .)
```

```{r}
vars <- str_subset(colnames(clinic2), "iga_")
list.map(
    vars,
    f(x, y) ~ {
        p <- mutate(clinic2, Group = !!sym(x)) %>%
            select(Group, groupe) %>%
            filter(groupe != "HD") %>%
            plot_bar_2cat(
                sort = c("DA", "PN"),
                colour = brewer.pal(6, "Reds")[-1] %>% rev(),
                colour_text = "black",
                legend = clinic2$iga_da %>% levels() %>% rev(),
                stats = FALSE,
                threshold_pct = 15,
                threshold = 1,
                width_title = 20,
                title = func_format2(x)
            ) + labs(y = NULL)
                if(y != 2)
                  p + theme(legend.position = "none")
                else
                  p
    }
) %>%
    plot_grid(plotlist = ., rel_widths = c(2, 2.75, 2))

res <- list.map(
  vars,
  f(x) ~ {
        select(clinic2, x, groupe, patient) %>%
    id_per_levels(colnames(.) %>% head(1), n_min = 5)
    }
)

res[seq(2)] %>%
    map(~mutate(., liste_patients = str_split(liste_patients, ",\\s*")) %>% pull(liste_patients)) %>%
    unlist() %>%
    metada_samples(clinic2, .)

filter(clinic2, groupe != "HD") %>%
  mutate(`.iga_post_ttt` = iga_post_ttt) %>%
  select(c(".iga_post_ttt", all_of(vars))) %>%
  rename_with(func_format) %>%
  rename_all(function(x) str_to_upper(x)) %>%
  plot_alluvial()

filter(clinic2, groupe != "HD") %>%
    select(c(all_of(vars), patient)) %>%
    rename_with(func_format) %>%
    rename_all(function(x) str_to_upper(x)) %>%
    filter(!is.na(`IGA POST TTT`)) %>% 
    relocate(`IGA POST TTT`)  %>%
    relocate(PATIENT) %>%
    arrange(`IGA POST TTT`) %>%
    kable0()

filter(clinic2, iga_post_ttt == "sévère") %>%
  pull(patient) %>%
  metada_samples(clinic2, .)

p <- list.map(
  c("DA", "PN"), 
  f(x) ~{
  if (x == "PN")
  vars1 <- c("iga_pn", str_subset(colnames(clinic2), "nb_nodules_"))
  else 
    vars1 <- NULL
  filter(clinic2, groupe == x) %>%
    plot_heatmap_clinic(c("iga_da", "sc_atteinte_percent", vars1))
  }
)

filter(clinic2, groupe == "DA") %>%
    plot_heatmap_clinic(c("iga_da", "sc_atteinte_percent", vars1), sort = c("5-30%", "30-50%", "> 50%", "modérée", "sévère", "très sévère"), colour = c(brewer.pal(4, "Reds")[-1], brewer.pal(4, "Purples")[-1]))

filter(clinic2, groupe == "PN") %>%
    plot_heatmap_clinic(c(str_subset(colnames(clinic2), "nb_nodules_"), "sc_atteinte_percent", "iga_pn", "iga_da") %>% rev(), sort = c("10-50", "> 50", "< 5%", "5-30%", "30-50%", "> 50%", "modérée", "sévère", "très sévère"), colour = c(brewer.pal(3, "Greens")[-1], brewer.pal(5, "Reds")[-1], brewer.pal(4, "Purples")[-1]))

cols_a_tester <- c("sc_atteinte_percent", "iga_da")#, "nb_nodules_actifs")
valeurs_cibles <- c("> 50%", "très sévère")#, "> 50")

lapply(seq_along(cols_a_tester), function(i) {
    col <- cols_a_tester[i]
    val <- valeurs_cibles[i]
    
    clinic2 %>%
        filter(groupe == "DA") %>%
        filter(.data[[col]] == val) %>%
        pull(patient)
}) %>%
  setNames(cols_a_tester) %>%
  plot_venn(n = 8)
```

```{r}
x <- "sc_atteinte_percent"
clinic2 %>%
  mutate(clinic2, Group = !!sym(x)) %>%
  select(Group, groupe) %>%
  plot_bar_2cat(
    sort = c("DA", "PN"),
    colour = brewer.pal(6, "Reds")[-1] %>% rev(),
    colour_text = "black",
    legend = pull(clinic2, x) %>% levels() %>% rev(),
    stats = FALSE,
    threshold_pct = 15,
    threshold = 1,
    width_title = 20,
    title = func_format(x) %>% 
      str_replace_all("percent", "\\(%\\)")
)
# severe: > 30

select(clinic2, x, groupe, patient) %>%
    id_per_levels(colnames(.) %>% head(1), n_min = 5)
```

```{r}
name_levels <- levels(clinic2$nb_nodules_pn)
list.map(
   str_subset(colnames(clinic2), "nb_nodules_"),
    f(x) ~ {
        mutate(clinic2, Group = !!sym(x)) %>%
            filter(groupe == "PN") %>%
            pull(Group) %>%
      plot_pie(
        colour = brewer.pal(length(name_levels) + 1, "Reds")[-1] %>% rev(),
        cex = 25,
        digits = 1,
        hsize = 1.5,
        legend = rev(name_levels),
        title = func_format(x) %>%
          str_replace_all("pn", "PN")
    )
    }
   
) %>%
    plot_grid(plotlist = ., nrow = 2, align = "hv")
```

```{r, eval = FALSE}
menopause
```

## Comorbidities
```{r}
vars <- c(
  "comorbidites",
  "hta",
  "diabete",
  "immunodepression",
  "autres_comorbidites"
)
vars <- c(
  "menopause",
  "ttt_chroniques",
  "atb_1mois",
  "derniere_douche_12h",
  "dernier_emollient_12h"
)
vars1 <- vars[seq(3)]
clinic3 <- select(clinic2, vars, "patient", "groupe") %>%
    rename_with(~str_replace(., "hta", "hypertension") %>% str_replace(., "1", "<1") %>% str_replace("atb", "antibiotique") %>% str_replace("ttt", "traitements"), everything())

select(clinic3, vars1, "groupe") %>%
  plot_bar_2cat_clinic(colnames(.) %>% discard(~str_detect(., "groupe"))) %>% 
    map(~ .x + labs(y = NULL)) %>%
{
  c(map(head(., -1), ~ .x + theme(legend.position = "none")), tail(., 1))
} %>%
    plot_grid(plotlist = ., nrow = 1, rel_widths = c(rep(1, length(vars1) -1), 1.3), align = "h")
```

```{r}
(res <- clinic3 %>%
   id_per_levels(colnames(.) %>% head(length(vars)), n_min = 5))

res2 <- filter(res, groupe == "DA") %>%
  filter((variable %in% c("menopause", "traitements_chroniques", "antibiotique_<1mois")  & levels == "Yes") | (variable %in% c("derniere_douche_<12h", "dernier_emollient_<12h") & levels == "No")) %>%
  # filter(levels == "Yes") %>%
    select(variable, liste_patients) %>%
    mutate(liste_patients = str_split(liste_patients, ",\\s*")) %>%
  mutate(variable = func_format(variable)) %>%
    deframe() %>%
    as.list()
plot_venn_clinic(res2, n_max = 5, width_label = 15)
```

```{r}
custom_upset_barplot(res2, ratio = 1)
extract_combination(res2)
```


```{r}
mutate(clinic3, `.diabete` = diabete) %>%
  select(c(".diabete", all_of(vars))) %>%
  rename_with(func_format) %>%
  plot_alluvial()
```

```{r, fig.width = 20, fig.height = 10}
clinic3 %>%
    plot_heatmap_clinic(colnames(.) %>% head(length(vars)), width_text = 50)
```

```{r}
# ids <- c("DA03", "DA04", "DA44", "DA31", "HD07")
ids <- c("PN02", "PN03", "PN07", "PN11", "PN13", "PN19", "PN30", "PN37")

metada_samples(clinic2, ids)
```

```{r}
clinic2$temps_dp_dernier_emollient_heures <- clinic2$temps_dp_dernier_emollient_heures %>% str_remove_all("> ?") %>% as.numeric()

vars <- c(
  #"temps_dp_derniere_at_bttt_sem",
  "temps_dp_derniere_douche_heures",
  "temps_dp_dernier_emollient_heures"
)

select(clinic2, vars, groupe, patient) %>%
    rename_with(~str_replace_all(., "dp_", "depuis_") %>% str_replace_all("heures", "(h)")) %>%
  plot_violin_group(., colnames(.) %>% head(2)) %>%
  map(~ .x + geom_hline(yintercept = 12, linetype = 2, linewidth = 1)) %>%
    plot_grid(plotlist = .)
```

```{r, fig.width = 20, fig.height = 10}
plot_heatmap_clinic(clinic2, vars)
```

```{r}
var <- "derniere_douche"
clinic2 %>% mutate(calculated = ifelse(!!sym(paste0("temps_dp_", var , "_heures")) < 12, "No", "Yes")) %>% select(all_of(c(paste0(var, "_12h"), "calculated"))) %>% set_colnames(c("Observed", "Calculated")) %>% plot_alluvial() + labs(title = func_format(var))
```

## Traitements
```{r}
vars <- c(
  "ttt_topiques",
  "dctc",
  "tacrolimus_topique",
  "autres_ttt_topiques",
  "ttt_systemique_1_mois",
  # "preciser_ttt_syst_1_mois",  # N = 1
  "photottt",
  "immunosuppresseurs",
  "ctc_systemique",
  "methotrexate",
  "autres_is",
  "preciser_immunosuppresseurs",
  "biottt",
  "dupilumab",
  "autre_biottt",
  "preciser_biottt",
  "autres_ttt"
  # "preciser_autre_ttt"
)

clinic2$preciser_biottt <- clinic2$preciser_biottt %>% str_remove_all(" durant.*")
clinic3 <- select(clinic2, c(all_of(vars), "groupe", "patient")) %>%
    rename_with(~ str_replace_all(.x, "_is", "_immunosuppresseurs") %>% str_replace_all("((bio)|(photo))ttt", "\\1therapie") %>% str_replace_all("ttt", "traitements") %>% str_replace_all("ctc", "corticoides topiques") %>% str_replace_all("d(corticoides)", "dermo\\1"))  %>%
    mutate(across(everything(), ~ str_replace_all(., "^0$", "No")))  %>%
    mutate(across(everything(), ~ str_replace_all(., "upilumab durant", "upilumab")))

ids <- seq(4); sort <- c("takrozem", "ANTIBIO")
ids <- 7:11; sort <- c("CTC PO", "methotrexate", "Tacrolymus", "thalidomide")
ids <- 12:15; sort <- c("dupilumab", "olumiant")
ids <- c(5:6, 16); sort <- NULL
ids <- c(1, 6:7, 12); sort <- NULL

filter(clinic3, groupe != "HD") %>%
  mplot_bar_2cat_clinic(colnames(.)[ids], sort = c("DA", "PN"))

filter(clinic3, groupe != "HD") %>%
  id_per_levels(colnames(.)[ids])

filter(clinic3, groupe == "DA") %>%
    plot_heatmap_clinic(
    colnames(.)[ids],
    colour = palette_discrete()[c(1, 3, 8, 2, 4, 5)],
    width_text = 100,
    sort = c("No", "Yes", sort)
  )

filter(clinic3, groupe == "DA") %>%
  id_per_levels(colnames(.)[ids], n_min = Inf) %>%
    filter(levels %in% c("Yes", sort)) %>%
    select(variable, liste_patients) %>%
    mutate(liste_patients = str_split(liste_patients, ",\\s*")) %>%
    mutate(variable = func_format(variable)) %>%
    deframe() %>%
    as.list() %>%
  split(names(.)) %>%
  map(~ unlist(.x) %>% unique()) %>%
  .[colnames(clinic3)[ids] %>% func_format()]  %>%
    compact() %>%
  plot_venn_clinic(n_max = 5, width_label = 15)
custom_upset_barplot()

c("PN17", "PN21", "PN01", "PN27") %>% 
  metada_samples(clinic2, ids = .)
#   "derniere_application_dctc",
# clinic2$temps_dp_dernier_emollient_heures <- clinic2$temps_dp_dernier_emollient_heures %>% str_remove_all("> ?") %>% as.numeric()

clinic3$immunosuppresseurs[which(clinic3$patient == "DA43")] <- "Yes"
```

## Samples
```{r}
vars <- c("pbmc", "serum", "plasma", "biopsie", "numeration", "swab") %>%
      c("dsq", ., paste0(., "_post_ttt"), "dsquame_post_ttt")
clinic2 <- mutate(clinic2, pbmc = pmbc)
list.map(
    vars,
    f(x, y) ~ {
        p <- mutate(clinic2, Group = !!sym(x)) %>%
            select(Group, groupe) %>%
            filter(groupe != "HD") %>%
            plot_bar_2cat(
                sort = c("DA", "PN"),
                legend = c("Yes", "No"),
                colour = palette_discrete()[c(3, 1)],
                colour_text = "black",
                stats = FALSE,
                threshold_pct = 10,
                threshold = 1,
                digits = 0,
                title = func_format(x)
            )
        if(!y %in% c(4, 11)) {
          p + theme(legend.position = "none")
        } else {
          p
        }
    }
) -> p
plot_grid(plotlist = p[seq(7)], ncol = 4, rel_widths = c(rep(2, 3), 2.75))
plot_grid(plotlist = p[-seq(7)], ncol = 4, rel_widths = c(rep(2, 3), 2.75))
```

```{r, fig.width = 20, fig.height = 10}
plot_heatmap_clinic(clinic2, vars[seq(7)])
```

## Others
```{r, fig.width = 8, fig.height = 3.7}
vars <- c("ethnie", "da_pn")
select(clinic2, ethnie, phototype) %>%
  plot_alluvial()
```

```{r}
plot_bar_2cat_clinic(clinic2, vars, pct = FALSE) %>%
  plot_grid(plotlist = ., align = "hv")
```

```{r}
select(clinic2, vars, groupe, patient) %>%
    id_per_levels(colnames(.) %>% head(length(vars)), n_min = 5)

filter(clinic2, ethnie == "Caucasian" & phototype %in% 4:6) %>%
    select(patient, phototype) %>% arrange(phototype) %>% group_split(phototype) %>% map(~ .x %>% pull(patient))
```

## Atopie
```{r}
vars <- c("terrain_atopique", "asthme", "da", "rhinite_allergique", "conjonctivite_allergique", "terrain_atopique_fam_1er_degre")
plot_bar_2cat_clinic(clinic2, vars, pct = FALSE) %>%
  plot_grid(plotlist = ., align = "hv")

res <- select(clinic2, vars, groupe, patient) %>%
    id_per_levels(colnames(.) %>% head(length(vars)), n_min = 4)
res
mutate(res, liste_patients = str_split(liste_patients, ",\\s*")) %>%
    filter(groupe == "HD") %>%
    select(variable, liste_patients) %>%
    deframe() %>%
    set_names(names(.) %>% func_format()) %>%
  plot_venn(width_label = 15)
```

```{r, fig.width = 20, fig.height = 10}
filter(clinic2, groupe == "HD") %>% plot_heatmap_clinic(vars, colour = palette_discrete()[c(1, 3)], width_text = 100, sort = c("No", "Yes"))

filter(clinic2, terrain_atopique == "No" & terrain_atopique_fam_1er_degre == "Yes") %>% metada_samples(ids = pull(., "patient"))
filter(clinic2, terrain_atopique == "Yes" & da == "No") %>% metada_samples(ids = pull(., "patient"))
```


```{r}
res2 <- select(clinic2, vars, groupe, patient) %>%
    id_per_levels(colnames(.) %>% head(length(vars)), n_min = Inf) %>%
  filter(levels == "Yes") %>%
  filter(groupe == "DA") %>%
  select(variable, liste_patients) %>%
    mutate(liste_patients = str_split(liste_patients, ",\\s*")) %>%
  mutate(variable = func_format(variable)) %>%
    deframe() %>%
    as.list()
custom_upset_barplot(res2, ratio = 1, width = 30)
extract_combination(res2)
```

```{r, fig.width = 8, fig.height = 3.7}
vars <- c("terrain_atopique_fam_1er_degre", "da", "terrain_atopique")
mutate(clinic2, `.terrain_atopique` = terrain_atopique) %>%
  select(c(".terrain_atopique", all_of(vars))) %>%
  rename_with(func_format) %>%
  plot_alluvial()
```

## Missing variables
```{r}
vis_miss(clinic2) + 
    theme(
    axis.text.x = element_blank(),
    panel.grid = element_blank()
)

df_sub <- clinic2 %>%
  filter(groupe != "HD") %>%
  column_to_rownames("patient") %>%
    set_colnames(
      colnames(.) %>% 
        str_replace_all("_", " ") %>%
        to_title()
      )

p <- plot_missing(
  df_sub,
  cex = .1,
  all = TRUE,
  sort = "asc",
  width_text = 50,
  label_x = "none",
  factor(df_sub$Groupe, labels = palette_discrete()[seq(2)])
)
plot_missing(
    df_sub,
    cex = .8,
    n_max = 35,
    width_text = 50,
    label_y = "percent",
    threshold1 = nrow(df_sub)/2,
    threshold2 = ncol(df_sub)/2,
    colour = factor(df_sub$Groupe, labels = palette_discrete()[seq(2)])
)
p2 <- plot_outliers(df_sub, cex = 8, n_max = 20)

list.map(
  list(p, p2),
  f(x) ~
    filter(clinic2, patient %in% names(head(x))) %>%
      metada_samples(ids = pull(., "patient"))
)

res <- extract_rare(df_sub) %>% 
    map(~ .x %>% filter(!rownames(.x) %in% "PN09")) %>%
    keep(function(x) nrow(x) > 0) %>%
    map(print_multinomial) %>%
    list.rbind()

res %>% 
    filter(!is.na(Levels)) %>%
    pull(Variables) %>% unique()
```

## Session information
```{r end, echo = FALSE}
sessionInfo()
```
